config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users, path: 'auth'

  root 'home#index'

  resources :feeds
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feed.rb
# frozen_string_literal: true

class Feed < ApplicationRecord
  belongs_to :user

  validates :url, presence: true, uniqueness: {
    scope: :user_id,
    message: I18n.t('feeds.feed_uniqueness_validation_message'),
    allow_blank: true
  }, http_url: {
    allow_blank: true
  }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pundit::Authorization

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = I18n.t('authorization.user_not_authorized')
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/feeds_controller.rb
# frozen_string_literal: true

class FeedsController < ApplicationController
  before_action :set_feed, only: %i[show edit update destroy]
  before_action :authenticate_user!
  after_action :verify_policy_scoped, only: %i[index show edit update destroy]

  # GET /feeds or /feeds.json
  def index
    @feeds = policy_scope(Feed).all
  end

  # GET /feeds/1 or /feeds/1.json
  def show; end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit; end

  # POST /feeds or /feeds.json
  def create
    @feed = add_new_feed

    respond_to do |format|
      if @feed.persisted?
        format.html { redirect_to feed_url(@feed), notice: I18n.t('feeds.feed_created') }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1 or /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(update_feed_params)
        format.html { redirect_to feed_url(@feed), notice: I18n.t('feeds.feed_updated') }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1 or /feeds/1.json
  def destroy
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url, notice: I18n.t('feeds.feed_destroyed') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_feed
    @feed = policy_scope(Feed).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def update_feed_params
    params.require(:feed).permit(:title, :subtitle)
  end

  def create_feed_params
    params.require(:feed).permit(:url)
  end

  def add_new_feed
    UseCases::AddNewFeed.call(url: create_feed_params.fetch(:url), user: current_user)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  DEFAULT_SVG_OPTS = { class: 'w-5 h-5' }.freeze

  def svg(name, opts = {})
    Rails.root.join("app/assets/images/#{name}.svg").to_s.then do |file_path|
      if File.exist?(file_path)
        Rails.cache.fetch("application_helper/svg/#{name}", expires_in: 3.minutes) do
          content_tag(:span, File.read(file_path).html_safe, svg_tag_opts(name, opts)) # rubocop:disable Rails/OutputSafety
        end
      else
        Rails.logger.error("Could not find svg: #{name}.svg")
        '(svg not found)'
      end
    end
  end

  private

  def svg_tag_opts(name, opts = {})
    DEFAULT_SVG_OPTS.merge(opts).tap do |o|
      o[:class] = "icon icon-#{name} #{o[:class]}"
    end
  end
end

app/helpers/feeds_helper.rb
# frozen_string_literal: true

module FeedsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/feeds/_feed.html.erb
<div id="<%= dom_id feed %>" class="card my-5 pb-1">
  <% if action_name != "show" %>
    <%= link_to feed.title, feed, class: "link font-semibold text-lg" %>
  <% end %>

  <p class="mb-3">
    <%= feed.subtitle || '-' %>
  </p>

  <p class="mt-3 mb-3 text-sm">
    <%= link_to feed.url, class: "link", target: "_blank", rel: "noopener" do %>
      <%= svg("rss", class: "mr-1 text-orange-500") %>
      <span><%= feed.url %></span>
    <% end %>
  </p>

  <p class="my-3 text-right text-xs text-gray-500">
    <span title="Last updated at: <%= feed.updated_at %>">
      <%= feed.updated_at %>
    </span>
  </p>

  <% if action_name == "foo" %>
    <%= link_to 'Edit', edit_feed_path(feed), class: "button link" %>
  <% end %>
</div>

app/views/feeds/_form.html.erb
<%= form_with(model: feed, class: "contents") do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation" class="alert alert-error mt-3">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% feed.errors.each do |error| %>
          <% if error.attribute == :url %>
            <li><%= error.attribute.upcase %> <%= error.message %></li>
          <% else %>
            <li><%= error.full_message %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% unless feed.new_record? %>
    <div class="my-5">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-field" %>
    </div>

    <div class="my-5">
      <%= form.label :subtitle, class: 'capitalize' %>
      <%= form.text_field :subtitle, class: "form-field" %>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :url, class: 'uppercase' %>
    <%= form.text_field :url, class: "form-field", disabled: feed.persisted? %>
  </div>

  <div class="inline">
    <%= form.submit feed.new_record? ? "Submit" : "Update", class: "button primary" %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="page-header">Editing feed</h1>

  <%= render "form", feed: @feed %>

  <div class="inline-block ml-2">
    <%= button_to 'Destroy',
        feed_path(@feed),
        data: { turbo_confirm: "Are you sure you wish to delete this feed?" },
        method: :delete,
        class: "button danger inverted" %>
  </div>
  <%= link_to "View Feed", @feed, class: "ml-2 button link" %>
  <%= link_to "Back to Feeds", feeds_path, class: "ml-2 button link" %>
</div>

app/views/feeds/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="page-header">My Feeds</h1>
    <%= link_to 'Add feed', new_feed_path, class: "button primary" %>
  </div>

  <div id="feeds" class="min-w-full">
    <%= render @feeds %>
  </div>
</div>

app/views/feeds/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="page-header">Add RSS Feed</h1>

  <%= render "form", feed: @feed %>

  <%= link_to 'Back to feeds', feeds_path, class: "ml-2 button" %>
</div>

app/views/feeds/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="mx-auto">
    <h1 class="page-header"><%= @feed.title %></h1>
    <%= render @feed %>

    <%= link_to 'Edit', edit_feed_path(@feed), class: "button link" %>
    <%= link_to 'Back to Feeds', feeds_path, class: "ml-2 button link" %>
  </div>
</div>

app/views/home/index.html.erb
<section class="grid max-w-screen-xl py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
  <div class="mr-auto place-self-center lg:col-span-7" data-aos="fade-up" data-aos-delay="100">
    <h1 class="max-w-2xl mb-4 text-4xl font-extrabold tracking-tight leading-none md:text-5xl xl:text-6xl dark:text-white">
      Stay Groovy,<br>
      Stay Updated
    </h1>

    <p class="mb-6 font-light text-gray-700 w-full sm:w-3/4 md:w-[80%] lg:w-5/6 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">
      From blogs to photos from outer space - RSS is everywhere. Just waiting
      to be tapped into.
    </p>

    <%= link_to user_signed_in? ? feeds_path : new_user_session_path, class: 'button primary large mb-2' do %>
      Get started
      <%= svg("arrow_right", class: "ml-2 -mr-1") %>
    <% end %>
  </div>
  <div class="hidden lg:mt-0 lg:col-span-5 lg:flex" data-aos="fade-up" data-aos-delay="300">
    <%= image_tag("home_hero.svg") %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reedr</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="turbo-cache-control" content="no-preview">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "https://ga.jspm.io/npm:aos@2.3.4/dist/aos.css" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="bg-zinc-100 dark:bg-gray-900">
<main class="container mx-auto mt-5 px-5">
  <div class="p-6">
    <nav class="mb-10 flex justify-between">
      <div class="text-3xl font-bold">
        <%= link_to root_path, class: 'text-primary-700 dark:text-primary-400 -skew-y-12 block' do %>
          Reedr
        <% end %>
      </div>

      <div class="flex items-center gap-3">
        <% if user_signed_in? %>
          <%= link_to feeds_path, class: 'button link', aria: { current: current_page?(feeds_path) } do %>
            <%= svg("list_icon", class: "mr-1") %>
            <span>My Feeds</span>
          <% end %>

          <%= button_to destroy_user_session_path, class: 'button', method: :delete do %>
            <%= svg("sign_out", class: "mr-1") %>
            <span>Sign Out</span>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path, class: 'button' do %>
            <%= svg("sign_in", class: "mr-1") %>
            <span>Sign In</span>
          <% end %>
        <% end %>
      </div>
    </nav>

    <div class="flash-messages" data-turbo-temporary>
      <% flash.each do |type, msg| %>
        <div class="flash flash-<%= type %>" data-controller="flash-message">
          <%= msg %>
          <button class="close" data-action="click->flash-message#yeet">
            <%= svg("close") %>
          </button>
        </div>
      <% end %>
    </div>

    <%= yield %>
  </div>

  <footer class="p-6 text-center text-xs text-gray-500">Powered by ☕️ and 🍕</footer>
</main>
</body>
</html>